# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.2]
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install
      run: |
        cd backend
        npm install
        
    - name: Run jest
      run: |
        cd backend
        npm test   
  cd:
    runs-on: ubuntu-latest
    needs: ci
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: build and push to docker
        uses: ./backend #/docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/backend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/backend:latest
      # - name: Docker login
      #   run: |
      #     echo "$PWD"
      #     docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      # - name: Build
      #   run: docker build -t back .
      # - name: Tags
      #   run: |
      #     docker tag back ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
      #     docker tag back ${{ secrets.DOCKER_USER }}/back:latest
      # - name: Push
      #   run: |
      #     docker push ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
      #     docker push ${{ secrets.DOCKER_USER }}/back:latest