name: ReactJS-Docker CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cd:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Tag
        run: |
          cd frontend
          docker build . --tag js-stack-frontend:v1
          docker tag js-stack-frontend:v1 ${{ github.actor }}/js-stack-frontend:v1
      - name: Push
        run: docker push ${{ github.actor }}/js-stack-frontend